name: CI Security Checks

on:
  push:
  pull_request:

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install SpotBugs
        run: |
          ./gradlew spotbugsMain spotbugsTest --stacktrace

      - name: Upload SpotBugs report
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: build/reports/spotbugs

      - name: Install OWASP Dependency-Check
        uses: jeremylong/gh-dependency-check@v5

      - name: Run Dependency-Check
        run: |
          dependency-check \
            --project "my-app" \
            --format "ALL" \
            --scan .

      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: ./dependency-check-report.*


      - name: Build with Gradle
        run: ./gradlew build --no-daemon
